services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: userssystem-web
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: production
    env_file:
      - .env
    restart: unless-stopped
