import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ToastContainer } from 'react-toastify'
import { ReactQueryProvider } from '@/providers/ReactQueryProvider'

import 'react-toastify/dist/ReactToastify.css';
import './globals.scss'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'UsersSystem',
  description: 'Generated by few159',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReactQueryProvider>
          {children}
        </ReactQueryProvider>
        <ToastContainer />
      </body>
    </html>
  )
}
